name: Push Workflow

on: [push]

jobs:
  build:
    strategy:
      matrix:
        repositories: ["discourse-subscriptions", "discourse-assign"]
    runs-on: [ubuntu-latest]
    steps:
      - name: copy workflows
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.github_token }}
          src_path: workflow-templates/.
          src_branch: main 
          dst_path: /.github/workflows/
          dst_owner: justindirose
          dst_repo_name: ${{ matrix.repositories }}
          file_filter: "*.yml"
