name: Push Workflow

on: 
  push:
    branches:
      - main
    paths:
      - 'workflow-templates/*.yml'

jobs:
  update-ci:
    strategy:
      matrix:
        repositories: ["discourse-subscriptions", "discourse-assign"]
    runs-on: [ubuntu-latest]
    steps:
      - env: 
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          REPO: ${{ matrix.repositories }}
        run: |
          git clone https://github.com/justindirose/.github ci
          echo "Cloning plugin"
          git clone https://$TOKEN@github.com/justindirose/$REPO plugin
          echo "Copying files"
          cp ci/workflow-templates/*.yml plugin/.github/workflows/
          echo "Committing changes"
          cd plugin
          git config user.email "ci@discourse"
          git config user.name "Discourse CI"
          git add -A
          git commit -m "Updates to CI workflows"
          git push origin master
