name: Push Workflow

on: 
  push:
    branches:
      - main
    paths:
      - 'workflow-templates/*.yml'

jobs:
  update-ci:
    strategy:
      matrix:
        repositories: ["discourse-subscriptions", "discourse-assign"]
    runs-on: [ubuntu-latest]
    steps:
      - name: Copycat Action
      # You may pin to the exact commit or the version.
      # uses: andstor/copycat-action@10a8fce94cc066110cb394d6f06814b7f5f06a34
      uses: andstor/copycat-action@v3.2.3
      with:
        # Personal access token
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        # The source path to the file(s) or folder(s) to copy from
        src_path: workflow-templates
        # The destination path to copy the file(s) or folder(s) to
        dst_path: .github/workflows
        # The name of the owner of the repository to push to
        dst_owner: justindirose
        # The name of the repository to push to
        dst_repo_name: ${{ matrix.repositories }}
        # The branch name of the source repository
        src_branch: main
        # The branch name of the destination repository
        dst_branch: master
        # A glob pattern for filtering file names
        file_filter: "*.yml"
