name: Push Workflow

on: 
  push:
    branches:
      - main
    paths:
      - 'workflow-templates/*.yml'

jobs:
  build:
    strategy:
      matrix:
        repositories: ["discourse-subscriptions", "discourse-assign"]
    runs-on: [ubuntu-latest]
    steps:
      - name: copy workflows
        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_TOKEN }}
        with:
          source_file: workflow-templates/test.yml 
          destination_repo: justindirose/${{ matrix.repositories }}
          destination-folder: .github/workflows
          user_email: 'ci@discourse'
          user_name: 'ci'
