name: Push Workflow

on: 
  push:
    branches:
      - main
    paths:
      - 'workflow-templates/*.yml'

jobs:
  update-ci:
    strategy:
      matrix:
        repositories: ["discourse-subscriptions", "discourse-assign"]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: checkout workflows
        uses: actions/checkout@v2
        with:
          path: ci
      - name: checkout plugin
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository: justindirose/${{ matrix.repositories }}
          path: plugin
      - name: copy files
        run: |
          [ ! -d "plugin/.github/workflows" ] && mkdir -p plugin/.github/workflows
          cp ci/workflow-templates/*.yml plugin/.github/workflows
      - name: create pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: Update CI
          committer: Discourse CI <ci@discourse>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: ci-update
          delete-branch: true
          body: |
            Update plugin linting and testing CI with latest workflows
            
