name: Push Workflow

on: 
  push:
    branches:
      - main
    paths:
      - 'workflow-templates/*.yml'

jobs:
  update-ci:
    strategy:
      matrix:
        repositories: ["discourse-subscriptions", "discourse-assign"]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: checkout workflows
        uses: actions/checkout@v2
        with:
          path: ci
      - name: checkout plugin
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository: justindirose/${{ matrix.repositories }}
          path: plugin
      - name: copy files
        run: |
          [ ! -d "plugin/.github/workflows" ] && mkdir -p plugin/.github/workflows
          cp ci/workflow-templates/*.yml plugin/.github/workflows
      - name: create PR
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          path: plugin
          branch: update-ci
          title: 'DEV: Update CI workflows'
          body: |
            Updates CI from discourse/.github
